[package]
name = "womp"
version = "0.1.0"
authors = ["Bret McGuire <bret.mcguire@gmail.com>"]

[dependencies]
procfs = "0.7.9"
partial_application = "0.2.0"
log = "0.4"
env_logger = "0.8.3"
clap = "3.0.0-beta.2"

[[bin]]
name = "cli"
path = "src/cli.rs"
